blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

blog/main/routes.py
import requests
from flask import render_template, request, Blueprint
from blog.models import Post

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    title = 'Mad-Blogger'
    return render_template('home.html', title=title, posts=posts)

@main.route('/quotes')
def quotes():
    url = 'http://quotes.stormconsultancy.co.uk/random.json'
    author = 'Jeff'
    quote = 'I just wanted to let you know that the second episode of Doctor Who season, titled "The Shakespeare Code'

    r = requests.get(url.format(author, quote)).json()
    
    quotes = {
        'author' : r['author'],
        'quote' : r['quote'],
    }
    print(quotes)
    return render_template('quotes.html', title='Random Quotes', quotes=quotes)


@main.route('/about')
def about():
    return render_template('about.html')

blog/posts/routes.py
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from blog import create_app, db
from blog.models import Post
from blog.posts.forms import PostForm


posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title = form.title.data, content = form.content.data, author = current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your blog has been uploaded', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title= 'New Post',
                            form=form, legend='New Post')

@posts.route('/post/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title='Post Title', post=post)



@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title= 'Update Post',
                            form=form, legend='Update Post')

@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from blog import db, bcrypt
from blog.models import User, Post
from blog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                RequestResetForm, ResetPasswordForm, NewsLetterForm)
from blog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Account created.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessfull.', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('account updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Login',
                            image_file=image_file, form=form)

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user - User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated. You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
            .order_by(Post.date_posted.desc())\
            .paginate(page=page, per_page=5)
    return render_template('user_posts.html', user=user, posts=posts)

@users.route('/newsletter', methods=['GET', 'POST'])
def newsletter():
    form = NewsLetterForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        flash('Email received. You will recieve newsletters.', 'success')
        return redirect(url_for('main.home'))
    return render_template('newsletter.html', form=form, title='Subscribe To Newsletters')

blog/templates/about.html
{% extends 'layout.html' %} {% block content %}
<h1 style="background-color: darkorange;">About Page</h1>
<p>an application where user can post different blogs and have them voted and commented on by other users</p>
{% endblock %}

blog/templates/account.html
{% extends 'layout.html' %} {% block content %}
<div class="card" style="padding: 10px;">
    <div class="media">
        <img src="{{ image_file }}" style="width: 100px; height: 100px;" alt="Cinque Terre">
        <div class="media-body ml-2">
            <h2 class="media-title">{{ current_user.username }}</h2>
            <p class="text-info"><i class="fa fa-envelope ml-2" aria-hidden="true"></i>{{ current_user.email}}</p>
        </div>
    </div>
    </br>
    <!-- Form -->
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"><i class="fa fa-user-circle" aria-hidden="true"></i>Account Info</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }} {% if form.username.errors %} {{ form.username(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.username(class="form-control form-control-lg") }} {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }} {% if form.email.errors %} {{ form.email(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.email(class="form-control form-control-lg") }} {% endif %}
            </div>
            <div class="form-group">
                {{ form.picture.label() }} {{ form.picture(class="form-control-file") }} {% if form.picture.errors %} {% for error in form.picture.errors %}
                <span class="text-info">{{ error }}</span></br>
                {% endfor %} {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-danger") }}
        </div>
    </form>
</div>
{% endblock %}

blog/templates/comment.html
{% extends 'layout.html' %} {% block content %}
<div class="card" style="padding: 10px;">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4 text-center">Comments</legend>
            <div class="form-group">
                {{ form.name.label(class="form-control-label") }} {% if form.name.errors %} {{ form.name(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.name.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.name(class="form-control form-control-lg") }} {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }} {% if form.email.errors %} {{ form.email(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.email(class="form-control form-control-lg") }} {% endif %}
            </div>
            <div class="form-group">
                {{ form.message.label(class="form-control-label") }} {% if form.message.errors %} {{ form.message(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.message.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.message(class="form-control form-control-lg") }} {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-danger") }}
        </div>
    </form>
</div>
{% endblock %}

blog/templates/create_post.html
{% extends 'layout.html' %}
{% block content %}
        <div class="card" style="padding: 10px;">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">{{ legend }}</legend>
                    <div class="form-group">
                        {{ form.title.label(class="form-control-label") }}
                        {% if form.title.errors %}
                            {{ form.title(class="form-control form-control-lg is-invalid")}}
                                <div class="invalid-feedback">
                                    {% for error in form.title.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.title(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.content.label(class="form-control-label") }}
                        {% if form.content.errors %}
                            {{ form.content(class="form-control form-control-lg is-invalid")}}
                                <div class="invalid-feedback">
                                    {% for error in form.content.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.content(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
{% endblock %}

blog/templates/home.html
{% extends 'layout.html' %} {% block content %} {% for post in posts.items %}
<div class="card">
    <article class="media ml-2">
        <img style="width: 180px; height: 270px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body" style="background-color: white;font-style: italic;border-radius: 5%;">
            <h5 class="mt-0"><a style="text-decoration: none; font-weight: 700; background-color:blueviolet;" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small><i class="text-primary ml-5"> Blog was Posted on {{ post.date_posted.strftime("%m/%d/%Y, %H:%M") }}</i></small></h5>
            <hr>
            <a href="{{ url_for('posts.post', post_id=post.id) }}" style="text-decoration: none; background-color: rgb(105, 224, 105);">
                <h6 style="font-weight: 700;">{{ post.title }}</h6>
            </a>
            <p>{{ post.content }}</p>
        </div>
    </article>
</div>
<br> {% endfor %} {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %} {% if page_num %} {% if posts.page == page_num %}
<!-- <a class="btn btn-success mb-4" style="background-color:blue;" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a> {% else %}
<a class="btn btn-outline-success mb-4" style="background-color: rgb(239, 243, 8);" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a> {% endif %} {% else %} ... {% endif %} {% endfor %} {% endblock %} -->

blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> {% if title %}
    <title>Welcome - {{ title }}</title>
    {% else %}
    <title>Blogz</title>
    {% endif %}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fontsCCESS
    .googleapis.com/css2?family=Inconsolata:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Bangers&family=BenchNine:wght@300&family=Caveat:wght@700&family=Righteous&display=swap" rel="stylesheet">
</head>

<body style="background-color: rgb(13, 210, 224);">
    <header class="site-header" style="background-color:rgb(204, 204, 243);">
        <nav class="navbar navbar-expand-lg">
            <div class="navbar-nav mr-auto">
                <h1 style="color:white ;text-align: center;">
                    BLOGZ.....
                </h1>
                <a href="{{ url_for('main.home') }}" class="nav-item nav-link" style="color:blue;"><i
                        class="fa fa-home mr-1" aria-hidden="true" style="color: rgb(214, 12, 123);"></i>Home</a>
                <a href="{{ url_for('main.about') }}" class="nav-item nav-link" style="color: blue;">About</a>
                <a href="{{ url_for('main.quotes') }}" class="nav-item nav-link" style="color:blue;">Generate blogs</a>
                <a href="{{ url_for('users.newsletter') }}" class="nav-item nav-link" style="color:blue;">Newsletter</a> {% if current_user.is_authenticated %}
                <a href="{{ url_for('posts.new_post') }}" class="nav-item nav-link" style="color: blue;">New Blog</a>
                <a href="{{ url_for('users.account') }}" class="nav-item nav-link" style="color:blue;">New Blog<i
                        class="fa fa-user mr-1" aria-hidden="true" style="color: white;"></i>Account</a>
                <a href="{{ url_for('users.logout') }}" class="nav-item nav-link" style="color:blue;"><i
                        class="fa fa-sign-out mr-1" aria-hidden="true" style="color: white;"></i>Logout</a> {% else %}
                <a href="{{ url_for('users.login') }}" class="nav-item nav-link" style="color: blue;">Login</a>
                <a href="{{ url_for('users.register') }}" class="nav-item nav-link" style="color: blue;"></a>Sign Up</a>
                {% endif %}
            </div>
        </nav>
    </header>
    <br>
    <div class="container" style="width:50%">
        <div class="row">
            <div class="col-md-12">
                {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %} {% endif %} {% endwith %} {% block content %} {% endblock %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

blog/templates/login.html
{% extends 'layout.html' %}
{% block content %}
        <div class="card" style="padding: 10px;">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Log In</legend>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid")}}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid")}}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                    <small class="text-muted ml-2">
                        <a href="{{ url_for('users.reset_request') }}">Forgot password?</a>
                    </small>
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Don't Have An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
                </small>
            </div>
        </div>
{% endblock %}

blog/templates/newsletter.html
{% extends 'layout.html' %}
{% block content %}
    <div class="card" style="padding: 10px;">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-center">Subscribe to Weekly Newsletters</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

blog/templates/post.html
{% extends 'layout.html' %} {% block content %}
<div class="card">
    <article class="media ml-2">
        <img class="rounded-circle mr-3 mt-2" style="width: 100px; height: 100px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
            <h5 class="mt-0"><a style="text-decoration: none; font-weight: 700;" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <!-- <small><i class="text-muted ml-5">Posted on {{ post.date_posted.strftime("%m/%d/%Y, %H:%M") }}</i></small></h5> -->
                {% if post.author == current_user %}
                <div>
                    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id = post.id) }}">Update</a>
                    <button type="button" class="btn btn-success btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
                {% endif %}
                <hr>
                <h6 style="font-weight: 700;">{{ post.title }}</h6>
                <p>{{ post.content }}</p>
        </div>
    </article>
</div>
<br>
<!-- Model -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method='POST'>
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/quotes.html
{% extends 'layout.html' %} {% block content %}
<div class="card" style="padding: 20px; background-color: rgb(78, 130, 202);">
    <blockquote class="blockquote-reverse">
        <p style="font-family: monospace; 
                    font-weight: 600;
                    color: rgb(238, 241, 245);
                    font-size: 16px;">
            <i class="fa fa-quote-left" aria-hidden="true" style="color: rgb(17, 27, 121); font-size: 26px;"></i></br>
            {{ quotes.quote }}</br>
            <i class="fa fa-quote-right pull-right" aria-hidden="true" style="color: rgb(19, 58, 185); font-size: 26px;"></i>
        </p>
        <footer class="blockquote-footer" style="color: rgb(25, 42, 190);
                        font-size: 20px;
                        font-weight: 500;
                        font-family: 'Inconsolata', monospace;
                        text-align: right;">
            {{ quotes.author }}
        </footer>
    </blockquote>
</div>
</br>
<div class="text-center">
    <h1 style="font-family: 'Righteous', cursive;">Refresh the page</h1>
    <h3 style="font-family: 'Caveat', cursive;">A new blog is displayed</h3>
    <h4 style="font-family: 'BenchNine', sans-serif;">blog on ..</h4>
</div>
{% endblock %}

blog/templates/reset_request.html
{% extends 'layout.html' %}
{% block content %}
        <div class="card" style="padding: 10px;">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Reset Password</legend>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid")}}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
{% endblock %}

blog/templates/user_posts.html
{% extends 'layout.html' %} {% block content %}
<h1 class="mb-3">Posts By: {{ user.username }} ({{ posts.total }})</h1>
{% for post in posts.items %}
<div class="card">
    <article class="media ml-2">
        <img class="rounded-circle mr-3 mt-2" style="width: 100px; height: 100px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
            <h5 class="mt-0"><a style="text-decoration: none; font-weight: 700;" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <!-- <small><i class="text-muted ml-5">Posted on {{ post.date_posted.strftime("%m/%d/%Y, %H:%M") }}</i></small></h5> -->
                <hr>
                <a href="{{ url_for('posts.post', post_id=post.id) }}" style="text-decoration: none;">
                    <h6 style="font-weight: 700;">{{ post.title }}</h6>
                </a>
                <p>{{ post.content }}</p>
        </div>
    </article>
</div>
<br> {% endfor %} {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %} {% if page_num %} {% if posts.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a> {% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a> {% endif %} {% else %} ... {% endif %} {% endfor %} {% endblock %}